services:
  banco_dados:
    image: mysql:8.0
    container_name: banco_dados_api
    environment:
      MYSQL_ROOT_PASSWORD: aluno
      MYSQL_DATABASE: banco_dados_api
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - minha_rede

  banco_dados_shadow:
    image: mysql:8.0
    container_name: banco_dados_api_shadow
    environment:
      MYSQL_ROOT_PASSWORD: aluno
      MYSQL_DATABASE: banco_dados_api_shadow
      MYSQL_USER: aluno
      MYSQL_PASSWORD: aluno
    ports:
      - "33307:3306"
    volumes:
      - mysql_data_shadow:/var/lib/mysql
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge

volumes:
  mysql_data:
  mysql_data_shadow:
